### ISSUE TITLE
询问

### ISSUE THREAD

**Issue by lhl19981130** [zhezhirenG/dunelr#1]
大佬您好，请问这个项目现在可以运行吗，我在本地跑起来找不到客户端文件夹和服务器文件夹。您可以说一下项目启动后具体的步骤吗，麻烦了

**Comment by uraurora** [comment]
非常抱歉，目前客户端和服务端还不可用，因为工作繁忙，代码很久未更新了。后续步骤其实比较清晰，我推荐你看一下rsync的同步步骤，原本的规划也是按照那个方案来进行同步的

**Comment by uraurora** [comment]
> 大佬您好，请问这个项目现在可以运行吗，我在本地跑起来找不到客户端文件夹和服务器文件夹。您可以说一下项目启动后具体的步骤吗，麻烦了

非常抱歉，目前客户端和服务端还不可用，因为工作繁忙，代码很久未更新了。后续步骤其实比较清晰，我推荐你看一下rsync的同步步骤，原本的规划也是按照那个方案来进行同步的
